# Generated by Django 2.0 on 2017-12-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=100)),
                ('is_published', models.BooleanField(default=True)),
                ('date_of_publication', models.DateTimeField()),
            ],
        ),
    ]
